services:
  postgres:
    image: postgres:latest
    env_file:
      - mainproject/docker.env
    ports:
      - "5432:5432"
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"
    command: -p 5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - mainproject/docker.env
    volumes:
      - .:/srv/app
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - postgres
    #command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn mainproject.wsgi:application --bind 0.0.0.0:8000 --timeout 250
volumes:
   postgresql-data:
   static-data:
     