# Generated by Django 5.2.4 on 2025-08-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('name', models.CharField(blank=True, default='', help_text='Enter your name', max_length=100, verbose_name='Name')),
                ('email', models.EmailField(blank=True, default='', help_text='Enter your email address', max_length=254, verbose_name='Email')),
                ('subject', models.CharField(blank=True, default='', help_text='Enter the subject', max_length=200, verbose_name='Subject')),
                ('message', models.TextField(blank=True, default='', help_text='Enter your message', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_date'],
            },
        ),
    ]
