# Generated by Django 5.2.4 on 2025-08-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Enter your name', max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='Enter the subject', max_length=254, verbose_name='Subject'),
        ),
    ]
