# Generated by Django 5.2.5 on 2025-08-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0002_rename_generalsettings_generalsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Enter the contact email address', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='parameter',
            field=models.CharField(blank=True, help_text='Enter any additional parameter', max_length=100, verbose_name='Parameter'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter the phone number', max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='site_description',
            field=models.TextField(blank=True, default='A short description about the site.', help_text='Enter a short description about the site', max_length=254, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='site_name',
            field=models.CharField(blank=True, default='SeçGEO', help_text='Enter the name of the site', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
