# Generated by Django 5.2.5 on 2025-08-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0003_alter_generalsetting_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='address',
            field=models.CharField(blank=True, help_text='Enter the address', max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='birthday',
            field=models.DateField(blank=True, help_text='Enter the birthday', null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='job_info',
            field=models.CharField(blank=True, default='Job Title', help_text='Enter the job information', max_length=100, verbose_name='Job Info'),
        ),
    ]
