# Generated by Django 5.2.5 on 2025-08-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0004_generalsetting_address_generalsetting_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='keywords',
            field=models.CharField(blank=True, default='hamdi,seçilmiş,map,harita,cbs,gps,gis,gnss,software,engineering SEO', help_text='Enter the keywords for the site', max_length=100, verbose_name='Keywords'),
        ),
    ]
