# Generated by Django 5.2.5 on 2025-08-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0005_generalsetting_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsetting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='generalsetting',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='generalsetting',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='generalsetting',
            name='job_info',
        ),
        migrations.RemoveField(
            model_name='generalsetting',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='generalsetting',
            name='phone_number',
        ),
    ]
