# Generated by Django 5.2.5 on 2025-08-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0006_remove_generalsetting_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='parameter',
            field=models.CharField(blank=True, help_text='Enter any additional parameter', max_length=254, verbose_name='Parameter'),
        ),
    ]
