# Generated by Django 5.2.5 on 2025-08-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0007_alter_generalsetting_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='parameter',
            field=models.TextField(blank=True, help_text='Enter any additional parameter', max_length=254, verbose_name='Parameter'),
        ),
    ]
