# Generated by Django 5.2.4 on 2025-08-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0008_alter_generalsetting_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='This is variable of the setting', max_length=254, verbose_name='Image Name')),
                ('description', models.TextField(blank=True, default='', help_text='This is variable of the setting', verbose_name='Image Description')),
                ('image_file', models.ImageField(default='', help_text='Upload an image file', upload_to='images/', verbose_name='Image File')),
            ],
        ),
    ]
