# Generated by Django 5.2.4 on 2025-08-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0009_imagesettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageSettings',
            new_name='ImageSetting',
        ),
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'ordering': ['-created_date'], 'verbose_name': 'General Setting', 'verbose_name_plural': 'General Settings'},
        ),
        migrations.AlterModelOptions(
            name='imagesetting',
            options={'ordering': ['name'], 'verbose_name': 'Image Setting', 'verbose_name_plural': 'Image Settings'},
        ),
    ]
