# Generated by Django 5.2.4 on 2025-08-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0010_rename_imagesettings_imagesetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesetting',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AddField(
            model_name='imagesetting',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date'),
        ),
    ]
