# Generated by Django 5.2.4 on 2025-08-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0011_imagesetting_created_date_imagesetting_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesetting',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='imagesetting',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
