# Generated by Django 5.2.4 on 2025-08-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0012_alter_imagesetting_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='imagesetting',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='imagesetting',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date'),
        ),
    ]
