# Generated by Django 5.2.4 on 2025-08-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0014_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('company_name', models.CharField(blank=True, help_text='Enter the name of the company', max_length=100, verbose_name='Company Name')),
                ('job_title', models.CharField(blank=True, help_text='Enter your job title', max_length=100, verbose_name='Job Title')),
                ('position', models.CharField(blank=True, help_text='Enter your position', max_length=100, verbose_name='Position')),
                ('start_date', models.DateField(blank=True, help_text='Enter the start date of your experience', null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=None, help_text='Enter the end date of your experience', null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-start_date'],
            },
        ),
    ]
