# Generated by Django 5.2.4 on 2025-08-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0015_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('school_name', models.CharField(blank=True, help_text='Enter the name of the institution', max_length=100, verbose_name='Institution Name')),
                ('department', models.CharField(blank=True, help_text='Enter your department', max_length=254, verbose_name='Department')),
                ('position', models.CharField(blank=True, help_text='Enter your position', max_length=100, verbose_name='Position')),
                ('start_date', models.DateField(blank=True, help_text='Enter the start date of your education', null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=None, help_text='Enter the end date of your education', null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['-start_date'],
            },
        ),
    ]
