# Generated by Django 5.2.4 on 2025-08-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0017_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('order', models.IntegerField(blank=True, default=0, help_text='Enter the order of the document', verbose_name='Order')),
                ('name', models.CharField(blank=True, default='', help_text='Enter the name of the document', max_length=100, verbose_name='Document Name')),
                ('button_text', models.CharField(blank=True, default='', help_text='Enter the button text', max_length=254, verbose_name='Button Text')),
                ('file', models.FileField(blank=True, help_text='Upload the document file', upload_to='documents/', verbose_name='Document File')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['order'],
            },
        ),
    ]
