# Generated by Django 5.2.4 on 2025-08-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0018_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Enter the slug for the document', max_length=100, verbose_name='Document Slug'),
        ),
    ]
