# Generated by Django 5.2.4 on 2025-08-11 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0019_document_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
    ]
