# Generated by Django 5.2.4 on 2025-08-13 16:31

import mainproject.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0020_remove_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Upload the document file', storage=mainproject.custom_storages.DocumentStorage(), upload_to='', verbose_name='Document File'),
        ),
        migrations.AlterField(
            model_name='imagesetting',
            name='image_file',
            field=models.ImageField(default='', help_text='Upload an image file', storage=mainproject.custom_storages.ImageSettingStorage(), upload_to='', verbose_name='Image File'),
        ),
    ]
